path: "D:/tuxiang GPU/datasets/coco_subset_seg"
train: images/train
val: images/val
test: images/test

names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: bus
  5: dog
  6: cat
  7: bottle
  8: chair
  9: laptop
